# Generated by Django 3.2.16 on 2022-11-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_settings'),
        ('users', '0022_auto_20221119_1819'),
    ]

    operations = [
    ]
