# Generated by Django 3.2.16 on 2022-11-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0056_alter_artist_content_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='copyright',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.TextField(),
        ),
    ]
